import { NextPage } from "next"

const Terms: NextPage = () => {
  return (
    <div style={{padding: '10px 50px'}}>
      <p style={{fontStyle: 'italic'}}>Condições de compra e emissão do certificado digital</p><br />
      <p>Para que nossos clientes não tenham dúvidas e estejam cada vez mais satisfeitos com nossos serviços e produtos, colocamos à disposição a política de garantia, com todas as informações úteis, em caso de necessidade de uso da garantia. Este documento visa esclarecer e centralizar as informações sobre a política de garantia das várias categorias de produtos comercializados pela BR CERTIFICADOS DIGITAIS.</p>
      <br />
      <p style={{fontStyle: 'italic'}}>Abrangência da Política de Garantia BR CERTIFICADOS DIGITAIS</p><br />
      <p>A Política de Garantia da BR CERTIFICADOS DIGITAIS é aplicável aos certificados validados, aos cartões inteligentes, ao tokens e às leitoras SD de cartão e está em conformidade com a legislação vigente do Código de Defesa do Consumidor.</p>
      <br />
      <p style={{fontStyle: 'italic'}}>Sobre o Código de Defesa do Consumidor</p><br />
      <p>O Código de Defesa do Consumidor – Lei 8.078/90 foi criado visando estabelecer regras de relacionamento entre empresas e consumidores. Essa legislação é uma das mais completas e preparadas para garantir a harmonia e o respeito mútuo no tratamento comercial entre aqueles que oferecem produto e serviços e aos consumidores finais. A política de garantia da BR CERTIFICADOS DIGITAIS foi planejada seguindo veementemente este conjunto de normas, e os profissionais de nossa empresa foram preparados para direcionar e solucionar as possíveis ocorrências com base no CDC e na legislação comercial. A BR CERTIFICADOS DIGITAIS  oferece garantia contra qualquer defeito de fabricação, desde que identificados dentro do prazo de garantia, conforme determina artigo 26 do Código de Defesa do Consumidor, contados a partir da data da aquisição do produto BR CERTIFICADOS DIGITAIS. Estão cobertos nessa garantia apenas os itens que comprovadamente apresentarem vícios, defeitos de fabricação, exceto os casos em que o defeito tenha sido causado por imperícia da pessoa que está realizando a instalação ou manuseio do produto entregue pela BR CERTIFICADOS DIGITAIS. Para requisitar qualquer tipo de atendimento de garantia, o produto deve ser levado a um dos pontos de atendimento da BR CERTIFICADOS DIGITAIS. Se esse procedimento não for cumprido e o consumidor adotar outros meios, a BR CERTIFICADOS DIGITAIS está apta a RECUSAR e devolver o produto.
        Garantia Contratual da BR CERTIFICADOS DIGITAIS: A garantia abrange somente defeitos de fabricação, isentando=se de qualquer imperícia, imprudência ou ainda mau uso do produto.
        Os contatos para mais informações sobre a politica de garantia, atendimentos de suporte e esclarecimentos de dúvidas podem ser feitos através da área de suporte da BR CERTIFICADOS DIGITAIS, podendo ser contatados através de nossas unidades de atendimento.</p>
      <br />
      <p style={{fontStyle: 'italic'}}>Cartão, leitora de cartao e token</p><br />
      <p>Os cartões, leitoras de cartão e tokens entregues pela BR CERTIFICADOS DIGITAIS têm garantia de 15 dias contra defeitos de fabricação, iniciados a partir da data da validação presencial. Os cartões e tokens são responsáveis pelo armazenamento e gerenciamento do certificado digital validado pela BR CERTIFICADOS DIGITAIS, evitando uso indevido. Esses dispositivos são protegidos por senhas: PIN senha do usuário solicitada toda vez que o certificado digital for utilizado; PUK senha de administração responsável pelo desbloqueio da senha PIN e cadastramento de nova senha PIN, sendo essas senhas de conhecimento único e exclusivo do responsável pelo certificado. Se defeitos de fabricação nos cartões e tokens criptográficos forem constatados pelo suporte técnico, dentro do prazo de garantia, será realizada a troca do dispositivo e substituição do certificado digital. Caso o suporte técnico identifique que o cartão foi bloqueado devido à inserção incorreta das senhas PIN e PUK, falhas de funcionamento decorrentes de insuficiência ou falta de fornecimento de energia elétrica, existência de objetos em seu interior estranhos ao seu funcionamento, imprudência ou imperícia no uso e manuseio do cartão ou token e danos causados pela natureza, a emissão de um novo certificado e o fornecimento de um novo cartão serão cobrados e estão condicionados ao agendamento do procedimento de validação presencial em um dos pontos de atendimento da BR CERTIFICADOS DIGITAIS. Ao ser constatado pela área de suporte técnico defeito de fabricação nas leitoras de cartão inteligente, durante o processo de vigência da garantia, será realizada substituição da leitora.</p>
      <br />
      <p style={{fontStyle: 'italic'}}>CERTIFICADO DIGITAL ICP-BRASIL</p><br />
      <p>A garantia dos certificados digitais ICP-Brasil do Tipo A-3 estará sujeita às condições de garantia dos cartões e tokens. A garantia dos certificados digitais ICP-Brasil do Tipo A-1 se inicia assim que o processo de validação presencial, em um dos pontos de atendimento da BR CERTIFICADOS DIGITAIS, é concluído. Os certificados do tipo A-1 são gerados e armazenados, o primeiro passo desse para dar andamento a esse processo é o cadastro da SENHA DE PROTEÇÃO, criada e cadastrada pelo consumidor. Isso garantirá que o par de chaves criptográficas seja gerado e, logo em seguida, armazenado no dispositivo removível. Durante esse mesmo processo, o consumidor também cadastrará a SENHA DE REVOGAÇÃO, necessária para emitir o certificado digital, após aprovação da autoridade certificadora, e revogação online (cancelamento) do certificado digital, durante seu período de validade. Assim que os processos de validação presencial, aprovação e assinatura forem concluídos, o certificado digital será transferido da autoridade certificadora diretamente para o dispositivo removível, sendo anexado ao par de chaves criptográficas.  A correta digitação das senhas irão configurar o teste do par de chaves e da senha, gerada pelo consumidor. <br />
        A BR CERTIFICADOS DIGITAIS não mantém cópia ou método de recuperação da senha gerada para proteção do par de chaves ou senha de revogação, cadastradas pelo titular ou responsável pelo uso do certificado digital. Se a senha de proteção for esquecida depois do processo de validação presencial, a reposição do certificado e do cartão não está coberta nas condições da política de garantia. Além disso, o esquecimento da senha de proteção impossibilita a instalação e configuração do certificado digital no computador que será usado pelo consumidor. A BR CERTIFICADOS DIGITAIS não mantém cópia do conteúdo gerado e armazenado dentro do dispositivo removível. Caso o dispositivo removível seja formatado ou seu conteúdo seja apagado total ou parcialmente fora do prazo de 15 dias a reposição do certificado e do conteúdo do dispositivo removível não está coberta nas condições da política de garantia. Uma vez que o certificado foi instalado, está armazenado e gerenciado pelo computador do consumidor, a BR CERTIFICADOS DIGITAIS não tem responsabilidade pelo uso e proteção do certificado. Caso o computador seja formatado ou substituído, é necessário que o certificado digital seja novamente instalado.
      </p>
      <br />
      <p style={{fontStyle: 'italic'}}>Emissão do Certificado Digital realizada pelo consumidor</p><br />
      <p>Durante o processo de validação presencial, em visita do agente de registro da São Paulo ao local determinado pelo consumidor, é configurada no computador, indicado pelo consumidor, a solicitação do certificado digital. Assim, o par de chaves criptográficas é gerado neste mesmo computador. É indispensável que todo o processo aconteça com o mesmo computador e usuário utilizados na validação presencial, sem alterações de configuração alguma. O processo de emissão será realizado pelo próprio consumidor, depois da visita do agente de registro da BR CERTIFICADOS DIGITAIS e, para isso, será enviado um e-mail, em até 24 horas úteis, com o link de aprovação de emissão, e passo a passo. (Entende-se por horas úteis: períodos de trabalho em dia de semana eletivo das 9:00 às 18:00 horas). Caso o computador, e para os certificados do tipo a-3 o computador e o cartão ou token, em que foi realizado o pedido seja formatado, roubado, sofra algum tipo de quebra, uso indevido, tenha problemas causados por mau uso, descarga elétrica, curto circuito ou desastres naturais que impossibilitem o seu uso com as mesmas condições em que foi realizada a solicitação do certificado, a ar meta certificadora se reserva o direito de não repor o certificado digital solicitado, pois essas condições não estão cobertas pela política de garantia.</p>
      <br />
      <p style={{fontStyle: 'italic'}}>CERTIFICADOS ICP-BRASIL, CARTÃO INTELIGENTE, LEITORA DE CARTÃO INTELIGENTE E TOKEN (Reembolso e Devoluções)</p><br />
      <p>O reembolso realizado pela BR CERTIFICADOS DIGITAIS será realizado ANTES da validação presencial do Certificado Digital. Para compras efetuadas através de cartão de crédito: 15 dias para solicitação. O prazo para crédito em conta é de até 2 (duas) faturas. Para compras efetuadas através de boleto: 15 dias para crédito na conta comprador. A solicitação de reembolso deverá ser realizada no prazo máximo de 30 (trinta) dias corridos, da data de pagamento do certificado digital. Caso o cliente não tenha realizado a emissão do seu certificado digital e este solicite o reembolso do mesmo num prazo após 30 (trinta) dias corridos, o cliente poderá usar o valor em créditos para a aquisição de outro certificado. </p>
      <br />
      <p style={{fontWeight: 'bold'}}>OBSERVAÇÃO: Todas as devoluções serão realizadas na conta corrente do comprador do certificado, conforme dados de faturamento informados na compra.</p><br />
    </div>
  )
}

export default Terms